export { default as Home } from './Home/Home';
export { default as About } from './About/About';
export { default as Contact } from './Contact/Contact';
export { default as FAQ } from './FAQ/FAQ';
export { default as Documentation } from './Documentation/Documentation';
export { default as PrivacyPolicy } from "./PrivacyPolicy/PrivacyPolicy"
export { default as DataPolicy } from "./DataPolicy/DataPolicy"
export { default as CookiePolicy } from "./CookiePolicy/CookiePolicy"
export { default as SignIn } from "./SignIn/SignIn"
export { default as SignUp } from "./SignUp/SignUp"